builds:
  - main: cmd/porcelain/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    files:
      - LICENSE
      - porcelain.tmux
      - porcelain.1
signs:
  - artifacts: checksum
